---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-parent
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $name, $config := .Values.parent.configs }}
  {{- if $config.enabled }}
  {{ $name }}: {{ tpl $config.data $ | toYaml | indent 4 }}
  {{- end }}
  {{- end }}

---

{{- if .Values.child.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-child
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $name, $config := .Values.child.configs }}
  {{- if $config.enabled }}
  {{ $name }}: {{ tpl $config.data $ | toYaml | indent 4 }}
  {{- end }}
  {{- end }}
{{- end }}

---

{{- if and .Values.child.enabled .Values.sd.child.enabled .Values.sd.child.configmap.from }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sd.child.configmap.name }}
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ .Values.sd.child.configmap.key }}: |
    {{- with .Values.sd.child.configmap.from }}
      {{- if and (.value) (kindIs "string" .value) }}
        {{- .value | nindent 4 }}
      {{- else if .value }}
        {{- toYaml .value | nindent 4 }}
      {{- else }}
        {{- $.Files.Get .file | nindent 4 }}
      {{- end}}
    {{- end}}
{{- end }}
