---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-slave
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  stream.conf: |-
    [stream]
        enabled = yes
        destination = {{ template "netdata.name" . }}:{{ .Values.service.port }}
        api key = 11111111-2222-3333-4444-555555555555
        timeout seconds = 60
        buffer size bytes = 1048576
        reconnect delay seconds = 5
        initial clock resync iterations = 60
  netdata.conf: |-
    [global]
        memory mode = ram
    [web]
        mode = none

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-master
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  stream.conf: |-
    [11111111-2222-3333-4444-555555555555]
        enabled = yes
        history = 3600
        default memory mode = ram
        health enabled by default = auto
        allow from = *
  netdata.conf: |-
    [global]
        memory mode = save
        bind to = 0.0.0.0:{{ .Values.service.port }}
        # this is a third test

